pbl6-E-Learning/PBL6

- server/.circleci/config.yml
> Add CircleCI configuration

- server/db/seeds.rb
- Backlog
Anh An vẫn cho số trong seed nha
> SCRUM-55 <seed data user>

- server/app/controllers/courses_controller.rb
- server/config/routes.rb
- server/db/seeds.rb
- server/spec/requests/courses_request_spec.rb
> SCRUM-57 <Show course>

- compose.yml
- server/Dockerfile
> SCRUM-86 <fix:Docker>

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/admin/users/page.tsx
- server/app/controllers/api/admin/accounts_controller.rb
- server/app/models/ability.rb
- server/app/models/account.rb
- server/config/routes.rb
- Backlog
https://github.com/user-attachments/assets/fc81970e-198c-408d-ad3e-18b51e4abad3
> SCRUM-35 <ban active>

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/user/courses/[id]/page.tsx
- server/app/controllers/api/application_controller.rb
- server/app/controllers/api/courses_controller.rb
- server/app/controllers/api/users_controller.rb
- server/app/models/ability.rb
- server/app/models/course.rb
- server/config/routes.rb
- server/db/seeds.rb
- server/spec/requests/course_assignments_request_spec.rb
- Backlog
https://github.com/user-attachments/assets/b785b7ed-d644-48f9-9022-e904bf69a161
https://github.com/user-attachments/assets/d506ad16-fe5b-4276-8be5-4ad89b94821f
> SCRUM-20 <ft: Assign_Course>

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/admin/courses/page.tsx
- client/src/components/CoursesTable/CoursesTable.tsx
- server/app/controllers/api/admin/courses_controller.rb
- server/config/routes.rb
- Backlog
https://github.com/user-attachments/assets/e890530b-8493-4bac-a6f3-3b447e6ee9c4
> SCRUM-82 ft: Delete Course Admin

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/admin/courses/page.tsx
- client/src/app/[locale]/login/page.tsx
- client/src/app/[locale]/signup/page.tsx
- client/src/app/[locale]/teacher/courses/index.ts
- client/src/app/[locale]/teacher/courses/page.tsx
- client/src/app/[locale]/teacher/index.ts
- client/src/app/[locale]/teacher/layout.tsx
- client/src/app/[locale]/teacher/page.tsx
- client/src/app/[locale]/user/progress/page.tsx
- client/src/app/types/courseProgress.type.ts
- client/src/components/Charts/ChartThree.tsx
- client/src/components/Charts/ChartTwo.tsx
- client/src/components/CoursesTable/CoursesTable.tsx
- client/src/components/MenuTeacher/Menu.tsx
- server/app/controllers/api/admin/users_controller.rb
- server/app/controllers/api/application_controller.rb
- server/app/controllers/api/teacher/application_controller.rb
- server/app/controllers/api/teacher/courses_controller.rb
- server/app/controllers/api/teacher/request_courses_controller.rb
- server/app/controllers/api/teachers_controller.rb
- server/app/models/ability.rb
- server/app/models/request_course.rb
- server/app/models/teacher.rb
- server/config/routes.rb
- server/db/migrate/20241015094223_create_request_courses.rb
- server/db/schema.rb
- server/spec/factories/request_courses.rb
- server/spec/models/request_course_spec.rb
- Backlog
https://github.com/user-attachments/assets/7e3e0251-274b-47dc-bcc7-bc02a2b20a4a
> SCRUM-27 <Create course request>

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/user/teacher/[id]/page.tsx
- server/app/controllers/api/admin/request_courses_controller.rb
- server/app/controllers/api/follows_controller.rb
- server/app/controllers/api/teachers_controller.rb
- server/app/mailers/user_mailer.rb
- server/app/models/ability.rb
- server/app/models/teacher.rb
- server/app/models/user.rb
- server/app/views/user_mailer/new_course_notification.html.erb
- server/app/views/user_mailer/new_course_notification.text.erb
- server/config/routes.rb
- server/config/settings.yml
- Backlog
https://github.com/user-attachments/assets/67a029fc-b4ea-4f7d-85f3-a0cba6767103
> SCRUM-101 <follow_teacher>

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/user/courses/[id]/page.tsx
- client/src/app/[locale]/user/lesson/[id]/index.ts
- client/src/app/[locale]/user/lesson/[id]/page.tsx
- client/src/app/[locale]/user/teacher/[id]/page.tsx
- client/src/app/hooks/service/teacher_infor.service.ts
- client/src/app/hooks/store.ts
- client/src/app/types/contentTypes.type.ts
- client/src/app/types/lesson.type.ts
- client/src/app/types/teacher.type.ts
- client/src/components/LessonScrollArea/LessonScrollArea.tsx
- server/app/controllers/api/courses_controller.rb
- server/app/controllers/api/lessons_controller.rb
- server/app/controllers/api/progress_controller.rb
- server/app/models/lesson.rb
- server/app/models/progress.rb
- server/config/routes.rb
- server/db/seeds.rb
- server/spec/requests/api/lessons_request_spec.rb
- Backlog
https://github.com/user-attachments/assets/c1f6c841-14ba-4e7c-ad04-bf779491aa03
https://github.com/user-attachments/assets/836d0674-ccb2-4c81-8a43-f37f2c399ac7
> SCRUM-22 <Page_Detail_Course>

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/teacher/page.tsx
- client/src/app/types/assignmentsCount.type.ts
- client/src/app/types/dashboardResponse.type.ts
- client/src/components/MenuTeacher/Menu.tsx
- client/src/components/TeacherChart/ChartOne.tsx
- client/src/components/TeacherChart/ChartThree.tsx
- client/src/components/TeacherChart/ChartTwo.tsx
- client/src/components/TeacherChart/Table.tsx
- server/app/controllers/api/instructor/courses_controller.rb
- server/app/controllers/api/lessons_controller.rb
- server/config/routes.rb
- server/spec/requests/api/teacher/dashboard_request_spec.rb
> SCRUM-104 <[Teacher] Dashboard>

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/teacher/courses/edit_course/[id]/index.ts
- client/src/app/[locale]/teacher/courses/edit_course/[id]/page.tsx
- client/src/app/[locale]/teacher/courses/page.tsx
- client/src/app/[locale]/user/layout.tsx
- client/src/components/CoursesTable/CoursesTable.tsx
- server/app/controllers/api/instructor/courses_controller.rb
- server/app/controllers/api/lessons_controller.rb
- server/app/models/course.rb
- server/config/routes.rb
- Backlog
https://github.com/user-attachments/assets/849f76b0-0455-42b6-ae29-98dabe94bcd7
> SCRUM-28 <ft: Edit Course Teacher>

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/teacher/courses/edit_course/[id]/page.tsx
- client/src/app/[locale]/teacher/lessons/add_lesson/[id]/index.ts
- client/src/app/[locale]/teacher/lessons/add_lesson/[id]/page.tsx
- client/src/app/types/lesson.type.ts
- server/app/controllers/api/instructor/lessons_controller.rb
- server/app/models/lesson.rb
- server/app/models/teacher.rb
- server/config/routes.rb
- server/db/migrate/20241025133035_rename_meaning_to_character_in_kanjis.rb
- server/db/schema.rb
- server/spec/requests/api/instructor/lessons_request_spec.rb
- Backlog
https://github.com/user-attachments/assets/4b306fff-62e4-432f-9e22-6c46759d6014
> SCRUM-31 <ft: Create Lesson Teacher>

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/teacher/courses/page.tsx
- client/src/app/[locale]/teacher/lessons/[id]/index.ts
- client/src/app/[locale]/teacher/lessons/[id]/page.tsx
- client/src/components/CoursesTable/CoursesTable.tsx
- client/src/components/LessonsTable/LessonsTable.tsx
- client/src/components/LessonsTable/index.ts
- server/app/controllers/api/instructor/lessons_controller.rb
- server/config/routes.rb
- Backlog
https://github.com/user-attachments/assets/58b6ab4e-e312-402b-8e71-a2f78e1c310d
https://github.com/user-attachments/assets/1bcb1924-96bf-4a0b-9ae1-8b85ab77608f
> SCRUM-106 SCRUM-33 <ft: list lesson + delete lesson>

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/account_confirmation_success/page.tsx
- client/src/app/[locale]/signup/page.tsx
- client/src/app/[locale]/teacher/courses/page.tsx
- client/src/app/[locale]/teacher/lessons/[id]/page.tsx
- client/src/app/[locale]/teacher/lessons/edit_lesson/[...params]/index.ts
- client/src/app/[locale]/teacher/lessons/edit_lesson/[...params]/page.tsx
- client/src/app/types/lesson.type.ts
- client/src/app/utils/http.ts
- server/app/controllers/api/instructor/lessons_controller.rb
- server/config/routes.rb
- Backlog
https://drive.google.com/file/d/1wNlE5FRByUtOpeIgCXqQGSf6mEX1zAs9/view?usp=sharing
> SCRUM-32 ft: Update Lessson Teacher

- .gitignore
- server/Gemfile
- server/Gemfile.lock
- server/app/models/course.rb
- server/spec/factories/accounts.rb
- server/spec/factories/categories.rb
- server/spec/factories/course_assignments.rb
- server/spec/factories/courses.rb
- server/spec/factories/teachers.rb
- server/spec/factories/users.rb
- server/spec/models/course_spec.rb
- server/spec/rails_helper.rb
- server/spec/spec_helper.rb
> SCRUM-126 <[Test] Course Model>

- server/spec/models/account_spec.rb
> SCRUM-125 <[Test] Account Model>

- server/spec/requests/courses_request_spec.rb
> SCRUM-122 <[Unittest] Course Controller>

- server/app/controllers/api/lessons_controller.rb
- server/spec/requests/lessons_request_spec.rb
> SCRUM-124 <[UnitTest] Lesson Controller>

- server/Gemfile
- server/Gemfile.lock
- server/app/controllers/api/progress_controller.rb
- server/spec/requests/courses_request_spec.rb
- server/spec/requests/progress_request_spec.rb
- server/spec/spec_helper.rb
> SCRUM-123 <[UnitTest] Progress Controller>

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/user/grammar/index.ts
- client/src/app/[locale]/user/grammar/page.tsx
- client/src/components/Navbar/Navbar.tsx
- client/src/components/TranslateForm/TranslateForm.tsx
- server/Gemfile
- Backlog
https://github.com/user-attachments/assets/549ebf74-57bb-4a11-b13c-4f049befa360
> SCRUM-113 ft_AI_bunpo

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/user/courses/[id]/page.tsx
- client/src/app/types/course.type.ts
- client/src/app/types/course_rating.type.ts
- client/src/components/CourseCard/CourseCard.tsx
- server/app/controllers/api/categories_controller.rb
- server/app/controllers/api/course_ratings_controller.rb
- server/app/controllers/api/courses_controller.rb
- server/app/controllers/api/users_controller.rb
- server/app/models/course.rb
- server/app/models/course_rating.rb
- server/app/models/user.rb
- server/config/routes.rb
- server/db/migrate/20241209035519_create_course_ratings.rb
- server/db/schema.rb
- server/spec/requests/course_ratings_request_spec.rb
- Backlog
https://github.com/user-attachments/assets/14d3b4e4-5501-42c8-be9e-deb629d0443d
**Bạn sửa lỗi CSS trong video rồi nha**
> SCRUM-99 ft: Rating_course

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/signup_teacher/index.ts
- client/src/app/[locale]/signup_teacher/page.tsx
- client/src/app/[locale]/teacher/profile/page.tsx
- client/src/app/types/profileRespone.type.ts
- client/src/components/NavbarAdmin/NavbarAdmin.tsx
- server/app/controllers/api/instructor/accounts_controller.rb
- server/app/controllers/api/instructor/application_controller.rb
- server/app/controllers/api/instructor/course_assignments_controller.rb
- server/app/controllers/api/instructor/courses_controller.rb
- server/app/controllers/api/instructor/lessons_controller.rb
- server/app/controllers/api/instructor/request_courses_controller.rb
- server/app/controllers/api/instructor/teachers_controller.rb
- server/app/controllers/api/users_controller.rb
- server/app/models/account.rb
- server/config/routes.rb
- server/spec/requests/api/instructor/accounts_request_spec.rb
- Backlog
https://drive.google.com/file/d/1RQCxJoNhQpitYGWNC77wuEizv6JWuwBJ/view?usp=sharing
> SCRUM-114 ft: register_teacher

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/admin/page.tsx
- client/src/app/[locale]/teacher/page.tsx
- client/src/app/[locale]/user/grammar/page.tsx
- client/src/app/types/dashboardResponse.type.ts
- client/src/components/AdminChart/ChartOne.tsx
- client/src/components/AdminChart/ChartThree.tsx
- client/src/components/AdminChart/ChartTwo.tsx
- client/src/components/AdminChart/Table.tsx
- client/src/components/KanjiList/KanjiList.tsx
- client/src/components/Menu/Menu.tsx
- client/src/components/MenuTeacher/Menu.tsx
- client/src/components/Navbar/Navbar.tsx
- client/src/components/Sidebar/Sidebar.tsx
- client/src/i18n/request.ts
- server/app/controllers/api/accounts_controller.rb
- server/app/controllers/api/admin/courses_controller.rb
- server/app/controllers/api/courses_controller.rb
- server/app/controllers/api/instructor/course_assignments_controller.rb
- server/app/models/account.rb
- server/config/routes.rb
- Backlog
https://github.com/user-attachments/assets/24b892c7-87b7-4d86-bcc5-cc0c5edd80c6
> SCRUM-105 ft: Dashboard Admin

- client/src/components/CourseCard/CourseCard.tsx
- server/app/controllers/api/authentication_controller.rb
- server/app/controllers/api/lessons_controller.rb
- server/app/controllers/api/users_controller.rb
> SCRUM-129 fix error

- client/messages/en.json
- client/messages/vi.json
- client/src/app/[locale]/admin/layout.tsx
- client/src/app/[locale]/user/grammar/page.tsx
- client/src/components/Menu/Menu.tsx
- client/src/components/Sidebar/Sidebar.tsx
> SCRUM-130 ft: Recommend

- server/app/controllers/api/users_controller.rb
- server/app/models/course.rb
> fix: distinct my course
